# Generated by Django 4.2.11 on 2026-06-17 06:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='Required when rejecting.')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'moderation_log',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
