# Generated by Django 4.2.11 on 2026-06-17 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='Cloudflare Stream / CDN URL')),
                ('video_id', models.CharField(blank=True, help_text='Provider video ID (e.g. Cloudflare Stream UID)', max_length=255)),
                ('duration_secs', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'episodes',
                'ordering': ['episode_number'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('drama', 'Drama'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('comedy', 'Comedy'), ('action', 'Action'), ('horror', 'Horror'), ('documentary', 'Documentary'), ('scifi', 'Sci-Fi'), ('other', 'Other')], default='other', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=False, help_text='Free to watch without subscription or purchase')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price for pay-per-series. 0 = subscription only.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'series',
                'db_table': 'series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_secs', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_records', to='content.episode')),
            ],
            options={
                'db_table': 'watch_history',
                'ordering': ['-watched_at'],
            },
        ),
    ]
