# Generated by Django 4.2.11 on 2026-06-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='series',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='users.producerprofile'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.series'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', 'watched_at'], name='watch_histo_user_id_1964c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'episode')},
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['status', 'genre'], name='series_status_7c0dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['producer', 'status'], name='series_produce_401ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['series', 'episode_number'], name='episodes_series__2c8d83_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('series', 'episode_number')},
        ),
    ]
